version: '1.0'
name: pipeline-20220716
displayName: pipeline-20220716
triggers:
  trigger: manual
  push:
    branches:
      prefix:
        - ''
stages:
  - name: stage-8b46aafe
    displayName: 未命名
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: build@maven
        name: build_maven
        displayName: Maven 构建
        jdkVersion: '8'
        mavenVersion: 3.3.9
        commands:
          - mvn -B clean package -Dmaven.test.skip=true
        artifacts:
          - name: BUILD_ARTIFACT
            path:
              - ./server/target
        settings: []
        caches:
          - ~/.m2
        notify: []
        strategy:
          retry: '0'
permissions:
  - role: admin
    members: []
