var vm = new Vue({
	el:"#app",
	data:{
		yuanshi:'YUANSHI',
		yuanshidir:[],
		selectyuanshi:[],
		pici:""
	},
	methods:{
		getDir:function(){
			dao.getDir({dir:this.yuanshi}).done(function(res){
				if(res.success){
					vm.yuanshidir=res.items;
					console.log(vm.yuanshidir)
				}else{
					alert("失败！")
				}
			})
		},
		getFull:function(){
			if(this.selectyuanshi.length==0){
				alert("至少选择一个批次");
			}else{
				dao.getFull({data:JSON.stringify(this.selectyuanshi),dir:this.yuanshi}).done(function(res){
					if(res.success){
						window.open(GLOBAL.URL+"ExcelSql/getFile?del=true&url="+res.fileName);
					}else{
						alert("出错！")
					}
				})
			}
		},
		upPici:function(){
			
		}
	},
	created(){
		this.getDir();		
	}
})