export default {
    baseURL:window.base.activityURL,
    imgURL:window.base.activityimgURL,
    code:'activity',
    activityAppointmentgetMyAct:'activityAppointment/getMyAct',
    activityAppointmenttoCancelApply:'activityAppointment/toCancelApply',
    activityTypelist:'activityType/list',//活动类别
    activityActivitylist:'activityAppointment/getMyAllAct',//全部活动列表
    activityAppointmenttoApply:'activityAppointment/toApply',//立即报名
    activityActivitygetCarousel:'activityActivity/getCarousel',//活动轮播图
    activityTypefindActivity:'activityType/findActivity',//发现活动
    activityActivitydetail:'activityActivity/detail',//活动详情
    activityActivitywonderfulReview:'activityActivity/wonderfulReview',//精彩回顾轮播
    activityFiledetailShow:'activityFile/listShow',//照片墙详情
    activityTextgetImgText:'activityText/getImgText',//图文详情
    activityAppointmentgetAppoint:'activityAppointment/getAppoint',//报名的表单
    activityAppointmentgetMyMonthAppoint:'activityAppointment/getMyMonthAppoint',//首页的日历
    getMonthAppoint:'activityActivity/getMonthAppoint',//首页的日历
}